Update article.php
situation: when you need use the site part com_content article model outside of com_content or calling model using 'ignore_request' => true

1. include the model require_once JPATH_SITE . '/components/com_content/models/article.php';
2. take instance of the model  $articlemodel = JModelLegacy::getInstance('Article', 'ContentModel', array('ignore_request' => true));
//see I used 'ignore_request' => true   and in such case the param object stored in state in null or not an object.
3. $articlemodel->setState('article.id', 1);  //suppose I need info for article of id 1 (i hard coded it for testing)
4.   $article = $articlemodel->getItem();  //get the information

Error: php error  " __clone method called on non-object in   ...." for line $data->params = clone $this->getState('params');  as the param object is empty and can not be clone. 

So the quick fix can be 

//$data->params = clone $this->getState('params');
$tempparams = $this->getState('params');
                if(is_object($tempparams)){
                    $data->params = clone $tempparams;
                }
                else{
                    $data->params = new Registry;
                }