Missing </div> into com_installer default.html
Missing </div> into file administrator/components/com_installer/views/install/tmpl/default.html

Step to reproduce

Go to the extension manager and check if with https://validator.w3.org/nu/

You will have a message such:
There is a missing html tag line 183 which produce error during W3C validation using https://validator.w3.org/nu/
Error: Unclosed element div.
From line 583, column 3; to line 583, column 44
</div> <div id="j-main-container" class="span10">

The proposal is to add the missing <div> on line 177

Expected result

No more error

Actual result

Error: Unclosed element div.

System information

Joomla 3.4.1